/* interjections.js -- Atmospheric interjection events (no mechanical effect). */

export const INTERJECTION_EVENTS = [
    {
        id: 'ij_vol_spike',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Your hands remember 2008. But this isn\'t 2008 — this is whatever Barron and al-Farhan are building between them. The screens are redder than you\'ve seen in months.',
        magnitude: 'minor',
        when: (sim) => Math.sqrt(sim.v) > Math.sqrt(sim.theta) * 2.5,
        params: {},
    },
    {
        id: 'ij_sidelines',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'You\'re watching from the sidelines while Lassiter passes tariffs and the tape runs without you. The Meridian Brief keeps printing. The desk keeps trading. You keep watching.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.positionCount === 0 && sim.day > 352,
        params: {},
    },
    {
        id: 'ij_own_press',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'You\'re starting to believe your own press. Three strong quarters. Sharma mentioned your desk in a MarketWire column. Cole wants an interview. Be careful.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.strongQuarters >= 3,
        params: {},
    },
    {
        id: 'ij_drawdown_hold',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Every fiber says cut it. But you\u2019ve been here before.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => {
            const equity = ctx.portfolio.equity;
            const peak = ctx.portfolio.peakEquity;
            return peak > 0 && (peak - equity) / peak > 0.15;
        },
        params: {},
    },
    {
        id: 'ij_quiet_tape',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Something feels wrong about this tape. The flow is too clean.',
        magnitude: 'minor',
        when: (sim) => sim.lambda > 3 && Math.sqrt(sim.v) < 0.15,
        params: {},
    },
    {
        id: 'ij_late_game',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Four years. Barron\'s term — your term — is ending. Lassiter, Okafor, Hartley, al-Farhan — all of them shaped the tape you traded. And you shaped it back.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => sim.day > 1152 && ctx.portfolio.impactTradeCount > 5,
        params: {},
    },
    {
        id: 'ij_negative_cash',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'The margin line is a cliff edge. You can feel the updraft.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.portfolio.cash < 0,
        params: {},
    },
    {
        id: 'ij_crisis_profits',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Someone is always on the other side of a crisis trade. Today it\'s pension funds in the Midwest, municipal bondholders in Ohio, Whittaker\'s constituents. You try not to think about it.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => sim.lambda > 5 && ctx.portfolio.pnlPct > 0.3,
        params: {},
    },
    {
        id: 'ij_empty_desk',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'The floor is quiet. The junior traders went home at six. The cleaning crew is vacuuming around you. The Meridian Brief won\'t publish for twelve hours. Just you and the screens and the numbers.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => sim.day > 752 && ctx.portfolio.positionCount > 10,
        params: {},
    },
    {
        id: 'ij_rate_negative',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Negative rates. The textbooks didn\u2019t prepare you for this.',
        magnitude: 'minor',
        when: (sim) => sim.r < 0,
        params: {},
    },
    // -- Faction/trait-aware interjections --
    {
        id: 'ij_political_exposure',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'You\'re in the rolodex now. Both parties. That\'s either leverage or liability.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) =>
            (ctx.factions.federalistSupport > 60 || ctx.factions.farmerLaborSupport > 60) && sim.day > 552,
        params: {},
    },
    {
        id: 'ij_firm_tension',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Webb\'s emails are shorter. Vasquez cancelled lunch. Riggs is smiling.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.factions.firmStanding < 35 && sim.day > 452,
        params: {},
    },
    {
        id: 'ij_ghost_trader',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Nobody knows your name. That used to bother you. Now it\'s the most valuable thing you own.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.traitIds.includes('quiet_money') && sim.day > 752,
        params: {},
    },
    {
        id: 'ij_media_target',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Tan mentioned you by name in last week\'s column. Your compliance officer sent you the clip with no comment.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.factions.mediaTrust > 65 && ctx.factions.regulatoryExposure > 40,
        params: {},
    },
    {
        id: 'ij_fed_whisper',
        category: 'interjection',
        interjection: true,
        likelihood: 1,
        headline: 'Hartley\'s office called again. The line between advising and insider is measured in basis points.',
        magnitude: 'minor',
        when: (sim, world, congress, ctx) => ctx.factions.fedRelations > 70 && !world.fed.hartleyFired,
        params: {},
    },
];
