/* =====================================================
   reference.js -- Reference overlay content for Shoals.

   Each key matches a data-info attribute in the HTML.
   Bodies use HTML with KaTeX math: $$...$$ for display,
   $...$ for inline. KaTeX loaded via CDN in index.html.
   ===================================================== */

export const REFERENCE = {

    // -----------------------------------------------------------------------
    // Pricing Models
    // -----------------------------------------------------------------------

    gbm: {
        title: 'Geometric Brownian Motion',
        body: `
<p>The stock price follows a continuous-time stochastic process that combines
deterministic drift with random diffusion and discrete jump events. This is the
foundation of all option pricing in the simulation.</p>

<h3>The Stochastic Differential Equation</h3>
$$\\frac{dS}{S} = (\\mu - q - \\lambda k)\\,dt + \\sqrt{v}\\,dW_1 + J\\,dN(\\lambda)$$
<p>Three forces act on the stock price at each instant:</p>
<ul>
<li><strong>Drift</strong> $(\\mu - q - \\lambda k)\\,dt$ &mdash; the expected return $\\mu$, reduced by the continuous
dividend yield $q$ and a jump compensator $\\lambda k$ that keeps the risk-neutral
expectation consistent after adding jumps.</li>
<li><strong>Diffusion</strong> $\\sqrt{v}\\,dW_1$ &mdash; the random component driven by a Wiener process $W_1$.
Note that $v$ is the instantaneous variance from the Heston model, not a constant &mdash;
the stock&rsquo;s volatility itself evolves stochastically.</li>
<li><strong>Jumps</strong> $J\\,dN(\\lambda)$ &mdash; discontinuous price moves arriving as a Poisson process
with intensity $\\lambda$. Each jump size is log-normal:
$\\ln(1 + J) \\sim \\mathcal{N}(\\mu_J,\\,\\sigma_J^2)$.</li>
</ul>

<h3>Itô&rsquo;s Lemma &amp; the Log-Price</h3>
<p>Applying Itô&rsquo;s lemma to $\\ln S$ yields the discrete-time update used in the simulation:</p>
$$\\ln S_{t+dt} = \\ln S_t + \\Big(\\mu - q - \\lambda k - \\tfrac{1}{2}v_t\\Big)\\,dt
+ \\sqrt{v_t}\\,\\sqrt{dt}\\,Z_1 + J \\cdot \\mathbb{1}_{\\{U < \\lambda\\,dt\\}}$$
<p>The $-\\tfrac{1}{2}v$ term is the Itô correction &mdash; it ensures that $E[S_{t+dt}/S_t] = e^{(\\mu - q - \\lambda k)\\,dt}$,
preventing the log-normal transformation from introducing drift bias.</p>

<h3>Jump Compensator</h3>
<p>The compensator $k = E[e^J - 1] = e^{\\mu_J + \\sigma_J^2/2} - 1$ is subtracted from the drift
so that jumps affect the variance of returns without changing the expected return.
When $\\mu_J < 0$, jumps are predominantly downward (crash risk), and the compensator
is negative, slightly increasing the effective drift to compensate.</p>

<h3>Correlated Brownian Motions</h3>
<p>The stock price and variance processes share correlated noise via Cholesky decomposition:</p>
$$Z_1 = \\epsilon_1, \\qquad Z_2 = \\rho\\,\\epsilon_1 + \\sqrt{1-\\rho^2}\\,\\epsilon_2$$
<p>where $\\epsilon_1, \\epsilon_2 \\sim \\mathcal{N}(0,1)$ are independent standard normals
generated by the Box-Muller transform. The interest rate process $W_3$ is independent.</p>

<h3>Simulation Discretisation</h3>
<p>The simulation uses 16 sub-steps per trading day, giving $dt = 1/4032 \\approx 0.000248$ years.
Each sub-step:</p>
<ol>
<li>Draw two independent normals via Box-Muller</li>
<li>Apply Cholesky correlation to get $Z_1, Z_2$</li>
<li>Update variance via Milstein scheme (see Heston reference)</li>
<li>Update log-price with drift + diffusion + possible jump</li>
<li>Update rate via Euler-Maruyama (see Vasicek reference)</li>
</ol>
<p>Poisson jump counts are computed via inverse-transform sampling:
$N = \\lfloor -\\ln(U) / (\\lambda\\,dt) \\rfloor$ for uniform $U \\in (0,1)$.</p>

<h3>Reset &amp; Prepopulation</h3>
<p>On reset, the stock initialises at $S = 100$, $v = \\theta$, $r = b$. The history is
backfilled by simulating 252 bars forward from the reset state, then reversing the
path to create a plausible prior history. This ensures the chart has a full year of
data from the start without introducing look-ahead bias.</p>
`,
    },

    heston: {
        title: 'Heston Stochastic Volatility',
        body: `
<p>In the Heston (1993) model, volatility is not constant &mdash; it follows its own mean-reverting
stochastic process correlated with the stock price. This produces the volatility smiles
and skews observed in real option markets, which constant-volatility models like
Black-Scholes cannot capture.</p>

<h3>Variance Dynamics</h3>
$$dv = \\kappa(\\theta - v)\\,dt + \\xi\\sqrt{v}\\,dW_2$$
<p>The variance $v$ is pulled toward the long-run level $\\theta$ at speed $\\kappa$.
The vol-of-vol parameter $\\xi$ controls how erratically volatility itself moves.
When $v > \\theta$, the drift is negative (variance decreasing); when $v < \\theta$, the drift
is positive (variance increasing).</p>

<h3>Milstein Discretisation</h3>
<p>The simulation uses the Milstein scheme with full truncation for the variance process:</p>
$$v_{t+dt} = v_t^+ + \\kappa(\\theta - v_t^+)\\,dt + \\xi\\sqrt{v_t^+}\\sqrt{dt}\\,Z_2
+ \\tfrac{1}{4}\\xi^2\\,dt\\,(Z_2^2 - 1)$$
<p>where $v_t^+ = \\max(v_t, 0)$ is the full truncation scheme. The Milstein correction
term $\\tfrac{1}{4}\\xi^2 dt(Z_2^2 - 1)$ improves accuracy over basic Euler-Maruyama by
capturing the curvature of $\\sqrt{v}$, and the result is floored at zero after each step.</p>

<h3>The Leverage Effect</h3>
<p>The correlation $\\rho = \\text{Corr}(dW_1, dW_2)$ is typically negative for equities
($-0.5$ to $-0.85$), meaning price drops tend to coincide with volatility spikes.
This is the &ldquo;leverage effect&rdquo;: falling prices increase financial leverage, which
increases perceived risk and option-implied volatility.</p>
<p>The consequence for option pricing: OTM puts become relatively more expensive than
OTM calls, producing a leftward-skewed volatility surface.</p>

<h3>Feller Condition</h3>
$$2\\kappa\\theta > \\xi^2$$
<p>When this inequality holds, the variance process is strictly positive &mdash; it never touches zero.
When violated, $v$ can hit zero and &ldquo;reflect&rdquo; (in continuous time) or go slightly negative
(in discrete simulation). The full truncation scheme handles this gracefully by flooring
$v$ at zero, but violation leads to a bimodal variance distribution with a mass near zero.</p>

<h3>Term-Structure Volatility</h3>
<p>The Heston model naturally generates a term structure of implied volatility. The expected
integrated variance over $[0, T]$ is:</p>
$$\\bar{v}(T) = \\theta + (v_0 - \\theta)\\frac{1 - e^{-\\kappa T}}{\\kappa T}$$
<p>Short-dated options see volatility close to $\\sqrt{v_0}$ (the current instantaneous vol),
while long-dated options see volatility converging toward $\\sqrt{\\theta}$ (the long-run level).
The simulation&rsquo;s <code>computeEffectiveSigma</code> uses this formula to set per-expiry ATM vol.</p>

<h3>Vol-of-Vol Convexity Correction</h3>
<p>When $\\xi > 0$, stochastic volatility introduces a convexity bias &mdash; the expected
integrated variance is higher than the naive deterministic path. The correction
(Gatheral 2006, Ch. 3; Lewis 2000, Sec. 5.3) adds:</p>
$$\\text{adj} = \\frac{\\xi^2}{2\\kappa^2} \\cdot w(\\kappa T), \\qquad
w(x) = \\frac{2(x - 1 + e^{-x})}{x^2}$$
<p>This lifts the entire volatility surface when vol-of-vol is significant.</p>

<h3>Moneyness Skew</h3>
<p>The per-strike volatility adjustment in the simulation uses a first-order approximation
of the Heston skew:</p>
$$\\sigma(K) \\approx \\sigma_{\\text{eff}} \\left(1 + \\frac{\\rho\\xi}{2\\sigma_{\\text{eff}}}
\\cdot d \\cdot \\ln\\frac{K}{S} + \\frac{\\xi^2}{12\\sigma_{\\text{eff}}^2}
\\cdot d \\cdot \\ln^2\\frac{K}{S}\\right)$$
<p>where $d = (1 - e^{-\\kappa T})/(\\kappa T)$ is the mean-reversion damping factor.
The first-order term produces the skew (driven by $\\rho$); the second-order term adds
symmetric curvature (the &ldquo;smile&rdquo; wings), driven by $\\xi^2$.</p>

<h3>Parameter Interactions</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Regime</th><th style="text-align:left;padding:4px 8px">$\\kappa$</th><th style="text-align:left;padding:4px 8px">$\\xi$</th><th style="text-align:left;padding:4px 8px">Behaviour</th></tr>
<tr><td style="padding:4px 8px">Calm market</td><td style="padding:4px 8px">High (3&ndash;5)</td><td style="padding:4px 8px">Low (0.1&ndash;0.3)</td><td style="padding:4px 8px">Vol stays near $\\theta$, shallow smile</td></tr>
<tr><td style="padding:4px 8px">Volatile</td><td style="padding:4px 8px">Low (0.5&ndash;1)</td><td style="padding:4px 8px">High (0.5&ndash;1.0)</td><td style="padding:4px 8px">Persistent wild swings, steep skew</td></tr>
<tr><td style="padding:4px 8px">Crisis</td><td style="padding:4px 8px">Very low</td><td style="padding:4px 8px">Very high</td><td style="padding:4px 8px">Vol explodes and stays elevated</td></tr>
</table>
`,
    },

    vasicek: {
        title: 'Vasicek Interest Rate Model',
        body: `
<p>The risk-free interest rate follows an Ornstein-Uhlenbeck process, the simplest
mean-reverting stochastic model for rates. This drives both the discount rate for
option pricing and the zero-coupon bond prices in the simulation.</p>

<h3>Rate Dynamics</h3>
$$dr = a(b - r)\\,dt + \\sigma_R\\,dW_3$$
<p>Three parameters govern the rate process:</p>
<ul>
<li>$a$ &mdash; mean-reversion speed. Higher $a$ pulls the rate back to $b$ more aggressively.</li>
<li>$b$ &mdash; long-run equilibrium rate. The unconditional expectation of $r$.</li>
<li>$\\sigma_R$ &mdash; rate volatility. Controls the magnitude of random fluctuations.</li>
</ul>
<p>The process $W_3$ is independent of the stock price ($W_1$) and variance ($W_2$)
Brownian motions.</p>

<h3>Negative Rates</h3>
<p>Unlike the Cox-Ingersoll-Ross (CIR) model, Vasicek permits negative interest rates.
This is a feature, not a bug &mdash; real rates can and do go negative (e.g., ECB deposit rate).
In the simulation, option pricing uses $r_{\\text{eff}} = \\max(r, 10^{-7})$ as a floor
to prevent degenerate behaviour in the binomial tree.</p>

<h3>Conditional Distribution</h3>
<p>The Vasicek model has a closed-form transition density. Given $r_t$:</p>
$$r_{t+\\Delta t} \\sim \\mathcal{N}\\Big(b + (r_t - b)e^{-a\\Delta t},\\;
\\frac{\\sigma_R^2}{2a}(1 - e^{-2a\\Delta t})\\Big)$$
<p>The simulation uses simple Euler-Maruyama discretisation:
$r_{t+dt} = r_t + a(b - r_t)\\,dt + \\sigma_R\\sqrt{dt}\\,Z_3$, which is adequate
at the small step size ($dt \\approx 1/4032$).</p>

<h3>Zero-Coupon Bond Pricing</h3>
<p>The Vasicek model admits an analytical bond pricing formula. A zero-coupon bond
maturing at time $T$ has price:</p>
$$P(r, T) = 100 \\cdot \\exp\\!\\Big(-B(T)\\,r - A(T)\\Big)$$
<p>where the duration measure $B(T)$ and the convexity correction $A(T)$ are:</p>
$$B(T) = \\frac{1 - e^{-aT}}{a}, \\qquad
A(T) = \\left(B(T) - T\\right)\\!\\left(b - \\frac{\\sigma_R^2}{2a^2}\\right)
- \\frac{\\sigma_R^2 B(T)^2}{4a}$$
<p>In the simulation, the simplified formula $P = 100 \\cdot e^{-rT}$ is used for bond pricing,
with duration capped at $B(T) \\leq 1/a$.</p>

<h3>Per-Step Rate Discounting</h3>
<p>The CRR binomial tree uses Vasicek per-step rate discounting rather than a flat rate.
At each tree step $i$, the local risk-free rate is:</p>
$$r_i = b + (r_0 - b)\\,e^{-a \\cdot i \\cdot dt}$$
<p>This gives each step its own discount factor $e^{-r_i\\,dt}$ and probability
$p_u^{(i)} = (e^{r_i\\,dt - q\\,dt} - d)/(u - d)$, capturing the term structure
within the tree itself.</p>

<h3>Duration &amp; Bond Sensitivity</h3>
<p>The effective duration of a zero-coupon bond in the Vasicek model is:</p>
$$D = B(T) = \\frac{1 - e^{-aT}}{a}$$
<p>As $T \\to \\infty$, duration saturates at $1/a$ &mdash; faster mean-reversion limits
the maximum duration. This contrasts with Macaulay duration ($= T$), which grows
without bound. Fast reversion ($a$ large) means rate shocks are transient and bond
prices recover quickly.</p>
`,
    },

    crr: {
        title: 'CRR Binomial Tree',
        body: `
<p>American options are priced using the Cox-Ross-Rubinstein (1979) binomial tree,
the workhorse model for American-style exercise where no closed-form solution exists.</p>

<h3>Tree Construction</h3>
<p>The stock price evolves on a recombining binomial lattice with $N = 128$ steps.
At each step, the price moves up by factor $u$ or down by factor $d$:</p>
$$u = e^{\\sigma\\sqrt{dt}}, \\qquad d = \\frac{1}{u} = e^{-\\sigma\\sqrt{dt}}, \\qquad dt = \\frac{T}{N}$$
<p>After $i$ up-moves and $n - i$ down-moves at step $n$, the stock price is:</p>
$$S_{n,i} = S_0 \\cdot u^{2i - n} \\cdot D_n$$
<p>where $D_n$ is the cumulative dividend adjustment factor (see below).</p>

<h3>Risk-Neutral Probabilities</h3>
<p>At each step $i$, the probability of an up-move is:</p>
$$p_u^{(i)} = \\frac{e^{(r_i - q)\\,dt} - d}{u - d}$$
<p>where $r_i$ is the Vasicek-implied rate at step $i$. The risk-neutral
measure ensures that the discounted stock price is a martingale.</p>

<h3>Backward Induction</h3>
<p>Option values propagate backwards from expiry to the present:</p>
$$V_{n,i} = \\max\\!\\Big(\\text{intrinsic}_{n,i},\\; e^{-r_n\\,dt}\\big(p_u V_{n+1,i+1} + (1-p_u) V_{n+1,i}\\big)\\Big)$$
<p>The $\\max$ with intrinsic value implements American early exercise &mdash; at every node,
the holder can exercise immediately or continue holding. European options omit
this $\\max$ and always continue.</p>

<h3>Discrete Dividends</h3>
<p>Proportional dividends of $q/4$ are applied at quarterly boundaries (every 63 trading days).
The dividend adjustment factor at step $n$ is:</p>
$$D_n = \\prod_{j \\leq n} (1 - q/4)^{\\mathbb{1}_{\\{\\text{step } j \\text{ is dividend date}\\}}}$$
<p>This multiplicatively reduces all stock prices beyond dividend dates, naturally
incorporating the discrete price drop into the tree without breaking recombination.</p>

<h3>Dual Call+Put Pricing</h3>
<p>For chain pricing, both call and put at each strike share a single backward induction
pass. At each node, the loop computes call intrinsic $\\max(S - K, 0)$ and put intrinsic
$\\max(K - S, 0)$ simultaneously, halving the number of tree traversals.
At 21 strikes per expiry, this saves 21 full backward inductions.</p>

<h3>Performance Optimisations</h3>
<ul>
<li><strong>Incremental $d^2$ stepping</strong>: Terminal node prices are computed as
$S \\cdot u^N$ then stepped down by $d^2$ instead of using $\\text{pow}(u, 2i-N)$,
reducing per-node cost by ~12&times;.</li>
<li><strong>Pre-allocated buffers</strong>: $\\texttt{Float64Array}$ buffers of size $N+1$
are reused across all pricing calls, eliminating GC pressure.</li>
<li><strong>Tree reuse API</strong>: <code>prepareTree()</code> precomputes $u^i$ powers, dividend
adjustments, and per-step discount factors once, then <code>priceWithTree()</code> reuses
them across all strikes at the same expiry.</li>
</ul>
`,
    },

    // -----------------------------------------------------------------------
    // Greeks
    // -----------------------------------------------------------------------

    delta: {
        title: 'Delta ($\\Delta$)',
        body: `
<p>Delta measures how much an option&rsquo;s price changes when the underlying stock price
moves by $1. It is the most fundamental Greek &mdash; the first-order sensitivity that
determines directional exposure.</p>

<h3>Definition</h3>
$$\\Delta = \\frac{\\partial V}{\\partial S}$$
<p>For European options under Black-Scholes:</p>
$$\\Delta_{\\text{call}} = e^{-qT}\\,N(d_1), \\qquad \\Delta_{\\text{put}} = -e^{-qT}\\,N(-d_1)$$
<p>where $d_1 = \\frac{\\ln(S/K) + (r - q + \\sigma^2/2)T}{\\sigma\\sqrt{T}}$ and $N(\\cdot)$ is
the standard normal CDF.</p>

<h3>Computation in This Simulation</h3>
<p>Since American options are priced via CRR binomial tree, delta is extracted directly
from the tree&rsquo;s first two time steps without additional backward inductions:</p>
$$\\Delta = \\frac{V_{1,1} - V_{1,0}}{S\\,(u - d)}$$
<p>where $V_{1,1}$ and $V_{1,0}$ are the option values at step 1 (up and down nodes),
$u$ and $d$ are the CRR up/down factors. This is equivalent to a central finite
difference with step $h = S(u - d)/2$.</p>

<h3>Interpretation</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Position</th><th style="text-align:left;padding:4px 8px">Delta range</th><th style="text-align:left;padding:4px 8px">Meaning</th></tr>
<tr><td style="padding:4px 8px">Long call</td><td style="padding:4px 8px">$0$ to $+1$</td><td style="padding:4px 8px">Bullish; gains when stock rises</td></tr>
<tr><td style="padding:4px 8px">Long put</td><td style="padding:4px 8px">$-1$ to $0$</td><td style="padding:4px 8px">Bearish; gains when stock falls</td></tr>
<tr><td style="padding:4px 8px">Short call</td><td style="padding:4px 8px">$-1$ to $0$</td><td style="padding:4px 8px">Bearish; mirror of long call</td></tr>
<tr><td style="padding:4px 8px">Short put</td><td style="padding:4px 8px">$0$ to $+1$</td><td style="padding:4px 8px">Bullish; mirror of long put</td></tr>
<tr><td style="padding:4px 8px">Long stock</td><td style="padding:4px 8px">$+1$</td><td style="padding:4px 8px">Constant delta of $+1$ per share</td></tr>
</table>

<h3>Moneyness &amp; Expiry Effects</h3>
<ul>
<li><strong>Deep ITM</strong>: Delta approaches $\\pm 1$ &mdash; the option behaves like the stock itself.</li>
<li><strong>ATM</strong>: Delta is near $\\pm 0.5$ &mdash; roughly a coin-flip on whether the option expires ITM.</li>
<li><strong>Deep OTM</strong>: Delta approaches $0$ &mdash; the option is insensitive to small price moves.</li>
<li><strong>Near expiry</strong>: Delta becomes more binary &mdash; sharply $0$ or $\\pm 1$ with a narrow transition zone near the strike.</li>
</ul>

<h3>Delta as Hedge Ratio</h3>
<p>Delta tells you how many shares to hold to neutralise directional risk.
To delta-hedge a short call with $\\Delta = 0.6$, buy 0.6 shares per option.
This creates a locally risk-free position (for small moves), but the hedge
must be rebalanced as the stock moves (because $\\Delta$ itself changes &mdash; see Gamma).</p>

<h3>Portfolio Delta</h3>
<p>The aggregate delta displayed in the Portfolio tab sums delta across all
option positions, weighted by quantity and multiplied by the option multiplier (1 in this sim).
A portfolio delta of $+50$ means $+\\$50$ P&amp;L per $\\$1$ stock move.</p>
`,
    },

    gamma: {
        title: 'Gamma ($\\Gamma$)',
        body: `
<p>Gamma is the rate of change of delta with respect to the stock price &mdash;
the second derivative of option value. It measures the <em>convexity</em> of the
option&rsquo;s payoff and determines how quickly the hedge ratio changes.</p>

<h3>Definition</h3>
$$\\Gamma = \\frac{\\partial^2 V}{\\partial S^2} = \\frac{\\partial \\Delta}{\\partial S}$$
<p>For European options under Black-Scholes:</p>
$$\\Gamma = \\frac{e^{-qT}\\,\\phi(d_1)}{S\\,\\sigma\\sqrt{T}}$$
<p>where $\\phi(\\cdot)$ is the standard normal PDF. Note that gamma is always the same
for a call and put at the same strike and expiry (put-call parity).</p>

<h3>Computation in This Simulation</h3>
<p>Gamma is extracted from the tree&rsquo;s first three time steps (steps 0, 1, 2):</p>
$$\\Gamma = \\frac{V_{2,2} - 2V_{2,1} + V_{2,0}}{\\big(S(u^2 - 1)/2\\big)^2}$$
<p>This uses the three step-2 node values to compute the second central finite difference,
requiring no additional backward inductions beyond the base pricing pass.</p>

<h3>Interpretation</h3>
<ul>
<li><strong>Long options</strong> (calls or puts) always have <strong>positive gamma</strong> &mdash; beneficial
convexity. Large moves in either direction help more than they hurt.</li>
<li><strong>Short options</strong> have <strong>negative gamma</strong> &mdash; harmful convexity.
Large moves amplify losses.</li>
<li><strong>Gamma is highest ATM</strong>, especially near expiry &mdash; this is where delta
changes most rapidly with the stock price.</li>
</ul>

<h3>The Gamma-Theta Trade-Off</h3>
<p>Gamma and theta are intimately linked. For a delta-hedged position:</p>
$$\\Theta \\approx -\\tfrac{1}{2}\\Gamma S^2 \\sigma^2$$
<p>Long gamma positions bleed theta (you pay time decay for the convexity benefit).
Short gamma positions earn theta (you collect premium but face large-move risk).
This is the fundamental trade-off in options: time decay vs. convexity.</p>

<h3>Gamma Risk Near Expiry</h3>
<p>As expiry approaches, ATM gamma spikes dramatically. A short ATM option position near
expiry is extremely dangerous &mdash; small price moves cause huge delta swings, making the
position unhedgeable in practice. This is &ldquo;pin risk&rdquo; &mdash; the stock may oscillate
around the strike, causing rapid alternation between ITM and OTM.</p>

<h3>Dollar Gamma</h3>
<p>Portfolio gamma in the simulation is reported as $\\Gamma \\times \\text{qty}$.
The dollar P&amp;L from gamma for a move $\\Delta S$ is approximately:</p>
$$\\text{P\\&L}_{\\gamma} \\approx \\tfrac{1}{2}\\,\\Gamma\\,(\\Delta S)^2$$
<p>This is always positive for long gamma (the portfolio benefits from large moves)
and always negative for short gamma.</p>
`,
    },

    theta_greek: {
        title: 'Theta ($\\Theta$)',
        body: `
<p>Theta measures time decay &mdash; the rate at which an option&rsquo;s value erodes as time
passes, holding all else constant. It answers: &ldquo;How much do I lose (or gain)
per day just by holding this position?&rdquo;</p>

<h3>Definition</h3>
$$\\Theta = \\frac{\\partial V}{\\partial t} = -\\frac{\\partial V}{\\partial T}$$
<p>The sign convention is: $\\Theta$ for long options is typically negative (value decreases
as time passes). For European calls under Black-Scholes:</p>
$$\\Theta_{\\text{call}} = -\\frac{S\\,e^{-qT}\\,\\phi(d_1)\\,\\sigma}{2\\sqrt{T}}
- rK\\,e^{-rT}\\,N(d_2) + qS\\,e^{-qT}\\,N(d_1)$$

<h3>Computation in This Simulation</h3>
<p>Theta is computed via central finite difference in time with step $h = 1/252$
(one trading day):</p>
$$\\Theta = \\frac{V(T - h) - V(T + h)}{2h}$$
<p>This requires two additional tree inductions &mdash; one at $T - h$ and one at $T + h$.
Near expiry, the step size is adjusted to prevent instability when $T < 2h$.</p>

<h3>Interpretation</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Position</th><th style="text-align:left;padding:4px 8px">Theta</th><th style="text-align:left;padding:4px 8px">Meaning</th></tr>
<tr><td style="padding:4px 8px">Long call/put</td><td style="padding:4px 8px">Negative</td><td style="padding:4px 8px">Loses value each day</td></tr>
<tr><td style="padding:4px 8px">Short call/put</td><td style="padding:4px 8px">Positive</td><td style="padding:4px 8px">Earns value each day (time decay works for you)</td></tr>
<tr><td style="padding:4px 8px">Deep ITM call</td><td style="padding:4px 8px">Near zero</td><td style="padding:4px 8px">Mostly intrinsic value; little time value to decay</td></tr>
<tr><td style="padding:4px 8px">ATM option</td><td style="padding:4px 8px">Most negative</td><td style="padding:4px 8px">Maximum time value = maximum decay rate</td></tr>
</table>

<h3>Theta Acceleration Near Expiry</h3>
<p>Time decay is not linear &mdash; it accelerates as expiry approaches. For ATM options,
theta is roughly proportional to $1/\\sqrt{T}$, meaning the last few days before
expiry see the steepest decay. An option that loses $\\$0.05$/day with 30 DTE
might lose $\\$0.25$/day with 2 DTE.</p>

<h3>The Theta-Gamma Relationship</h3>
<p>For a delta-neutral portfolio, the daily P&amp;L is approximately:</p>
$$\\text{P\\&L} \\approx \\Theta\\,dt + \\tfrac{1}{2}\\Gamma\\,S^2\\sigma^2\\,dt$$
<p>If realised volatility exceeds implied, the gamma term dominates and the position
profits despite theta bleed. If realised vol is lower, theta dominates. This is
the essence of volatility trading.</p>

<h3>Weekend &amp; Calendar Effects</h3>
<p>This simulation uses trading days (252/year), so theta applies uniformly across
all days. In real markets, theta for a Friday close accounts for three calendar days,
creating a &ldquo;weekend theta&rdquo; premium that market makers factor into their pricing.</p>
`,
    },

    vega: {
        title: 'Vega ($\\mathcal{V}$)',
        body: `
<p>Vega measures the sensitivity of an option&rsquo;s price to changes in implied volatility.
Despite not being an actual Greek letter, it is perhaps the most important Greek
for options traders, since volatility is the primary &ldquo;unknown&rdquo; in option pricing.</p>

<h3>Definition</h3>
$$\\mathcal{V} = \\frac{\\partial V}{\\partial \\sigma}$$
<p>For European options under Black-Scholes:</p>
$$\\mathcal{V} = S\\,e^{-qT}\\,\\phi(d_1)\\,\\sqrt{T}$$
<p>Like gamma, vega is identical for calls and puts at the same strike and expiry.</p>

<h3>Computation in This Simulation</h3>
<p>Vega is computed via central finite difference in volatility with step $h = 0.001$:</p>
$$\\mathcal{V} = \\frac{V(\\sigma + h) - V(\\sigma - h)}{2h}$$
<p>This requires two additional tree inductions with shifted volatility inputs.
The tree parameters (u, d, probabilities) are recomputed for each shifted vol.</p>

<h3>Interpretation</h3>
<ul>
<li><strong>Long options</strong> (calls or puts) have <strong>positive vega</strong> &mdash; they benefit from
rising volatility. If you expect vol to increase, buy options.</li>
<li><strong>Short options</strong> have <strong>negative vega</strong> &mdash; they lose when volatility rises.
If you expect vol to decrease, sell options.</li>
<li><strong>ATM options have the highest vega</strong> &mdash; deep ITM/OTM options are less
sensitive to vol changes.</li>
<li><strong>Longer-dated options have more vega</strong> &mdash; there is more time for volatility
changes to affect the outcome.</li>
</ul>

<h3>Vega in a Stochastic Volatility World</h3>
<p>In the Heston model used by this simulation, volatility is itself a random variable.
The $\\sigma$ used for Greek computation is the instantaneous $\\sqrt{v}$, which changes
every sub-step. This means vega exposure is dynamic &mdash; it shifts as the Heston variance
process evolves, unlike in a flat-vol model where vega is static.</p>
<p>Real option vega depends on the entire volatility surface (term structure and skew),
not just spot vol. The simulation captures some of this via the term-structure and
skew adjustments in <code>computeEffectiveSigma</code> and <code>computeSkewSigma</code>.</p>

<h3>Vega &amp; the Volatility Surface</h3>
<p>A portfolio might be vega-neutral to parallel shifts in the vol surface but still
exposed to changes in the slope (skew) or curvature (convexity) of the surface.
Higher-order sensitivities include:</p>
<ul>
<li><strong>Vanna</strong> $= \\partial\\Delta/\\partial\\sigma = \\partial\\mathcal{V}/\\partial S$ &mdash;
cross-sensitivity between price and vol.</li>
<li><strong>Volga (Vomma)</strong> $= \\partial^2 V/\\partial\\sigma^2$ &mdash; convexity in vol space.
Important for pricing risk of volatility-of-volatility.</li>
</ul>

<h3>Practical Use</h3>
<p>A vega of $0.15$ means the option price changes by $\\$0.15$ for each 1 percentage-point
change in implied volatility. If vol moves from 25% to 30% (a 5pp increase),
the option gains approximately $5 \\times 0.15 = \\$0.75$.</p>
`,
    },

    rho_greek: {
        title: 'Rho ($\\rho$)',
        body: `
<p>Rho measures the sensitivity of an option&rsquo;s price to changes in the risk-free
interest rate. It is often the &ldquo;forgotten Greek&rdquo; because rate changes are typically
small, but in the Vasicek rate environment of this simulation, rho exposure can
be significant.</p>

<h3>Definition</h3>
$$\\rho = \\frac{\\partial V}{\\partial r}$$
<p>For European options under Black-Scholes:</p>
$$\\rho_{\\text{call}} = KT\\,e^{-rT}\\,N(d_2), \\qquad \\rho_{\\text{put}} = -KT\\,e^{-rT}\\,N(-d_2)$$

<h3>Computation in This Simulation</h3>
<p>Central finite difference in $r$ with step $h = 0.0001$ (1 basis point):</p>
$$\\rho = \\frac{V(r + h) - V(r - h)}{2h}$$
<p>Two additional tree inductions with shifted rate inputs, including shifted
per-step Vasicek discounting throughout the tree.</p>

<h3>Interpretation</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Position</th><th style="text-align:left;padding:4px 8px">Rho sign</th><th style="text-align:left;padding:4px 8px">Why</th></tr>
<tr><td style="padding:4px 8px">Long call</td><td style="padding:4px 8px">Positive</td><td style="padding:4px 8px">Higher rates raise the forward price $\\Rightarrow$ call more valuable</td></tr>
<tr><td style="padding:4px 8px">Long put</td><td style="padding:4px 8px">Negative</td><td style="padding:4px 8px">Higher rates raise the forward $\\Rightarrow$ put less valuable</td></tr>
<tr><td style="padding:4px 8px">Short call</td><td style="padding:4px 8px">Negative</td><td style="padding:4px 8px">Mirror of long call</td></tr>
<tr><td style="padding:4px 8px">Short put</td><td style="padding:4px 8px">Positive</td><td style="padding:4px 8px">Mirror of long put</td></tr>
</table>

<h3>Rho &amp; the Vasicek Model</h3>
<p>In most trading simulations, the risk-free rate is constant, making rho nearly
irrelevant. Here, rates follow a Vasicek process that can move significantly &mdash;
from negative to 20% &mdash; making rho a meaningful source of P&amp;L.</p>
<p>Rate moves affect options through two channels:</p>
<ol>
<li><strong>Discounting</strong>: Higher rates reduce the present value of the strike (helping calls, hurting puts).</li>
<li><strong>Forward price</strong>: Higher rates increase the risk-neutral drift $r - q$, pushing the
expected future stock price higher.</li>
</ol>

<h3>Rho &amp; Duration</h3>
<p>Longer-dated options have more rho exposure because the discounting effect compounds
over more time. This is analogous to bond duration &mdash; a 1-year option has roughly 5&times;
the rho of a 2-month option. For very short-dated options, rho is negligible compared
to delta and gamma.</p>

<h3>Cross-Asset Rho Exposure</h3>
<p>A portfolio holding both options and zero-coupon bonds has compound rate sensitivity.
The bond&rsquo;s P&amp;L from a rate change $\\Delta r$ is approximately $-B(T) \\times P \\times \\Delta r$,
while each option contributes $\\rho \\times \\Delta r$. The portfolio&rsquo;s total rate exposure
is the sum of all these terms.</p>
`,
    },

    // -----------------------------------------------------------------------
    // Market Mechanics
    // -----------------------------------------------------------------------

    bidask: {
        title: 'Bid-Ask Spreads',
        body: `
<p>All instruments in the simulation trade with a bid-ask spread. You always buy at the
ask (higher price) and sell at the bid (lower price). The spread is the implicit
transaction cost of every trade.</p>

<h3>Spread Model</h3>
<p>The half-spread for stocks and bonds is:</p>
$$h = \\max\\!\\big(h_{\\min},\\; P_{\\text{mid}} \\times p \\times (1 + \\sigma)\\big)$$
<p>For options, an additional moneyness term widens the spread for deep ITM/OTM strikes:</p>
$$h = \\max\\!\\big(h_{\\min},\\; P_{\\text{mid}} \\times p \\times (1 + \\sigma)
+ w \\cdot |\\ln(S/K)|\\big)$$
<p>where:</p>
<ul>
<li>$h_{\\min}$ &mdash; minimum half-spread floor (prevents zero spreads on cheap options)</li>
<li>$p$ &mdash; base spread percentage</li>
<li>$\\sigma$ &mdash; current instantaneous volatility $\\sqrt{v}$</li>
<li>$w$ &mdash; moneyness spread weight</li>
<li>$|\\ln(S/K)|$ &mdash; log-moneyness distance from ATM</li>
</ul>

<h3>Why Spreads Widen</h3>
<p>Real market makers face adverse selection: informed traders pick them off when prices
are about to move. Higher volatility means larger potential losses per quote, so
market makers widen spreads to compensate. The simulation captures this: high-vol
environments have wider spreads, increasing transaction costs.</p>

<h3>Fill Prices</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Action</th><th style="text-align:left;padding:4px 8px">Fill price</th><th style="text-align:left;padding:4px 8px">Cost</th></tr>
<tr><td style="padding:4px 8px">Buy (long)</td><td style="padding:4px 8px">Ask = mid + $h$</td><td style="padding:4px 8px">Pay more than fair value</td></tr>
<tr><td style="padding:4px 8px">Sell (short/close)</td><td style="padding:4px 8px">Bid = mid &minus; $h$</td><td style="padding:4px 8px">Receive less than fair value</td></tr>
</table>
<p>The spread cost per round-trip (buy then sell) is $2h$. For a stock trading at
$\\$100$ with a 0.5% half-spread, each round-trip costs $\\sim\\$1.00$.</p>

<h3>Viewing Bid-Ask Prices</h3>
<p>Hover over any price cell in the chain to see the bid and ask prices in a tooltip.
The displayed price is always the theoretical mid-price (fair value).</p>
`,
    },

    margin: {
        title: 'Margin System',
        body: `
<p>The margin system enforces collateral requirements for leveraged positions,
preventing unlimited risk exposure. It models simplified Regulation T margin rules.</p>

<h3>Initial Margin</h3>
<p>New positions must satisfy initial margin requirements:</p>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Position type</th><th style="text-align:left;padding:4px 8px">Initial margin</th></tr>
<tr><td style="padding:4px 8px">Short stock/bond</td><td style="padding:4px 8px">50% of notional</td></tr>
<tr><td style="padding:4px 8px">Buying on margin (negative cash)</td><td style="padding:4px 8px">Equity $\\geq$ 50% of debit (Reg T)</td></tr>
<tr><td style="padding:4px 8px">Short options</td><td style="padding:4px 8px">$\\max(20\\% \\times S \\times |\\text{qty}|,\\; \\text{prem} \\times |\\text{qty}|)$</td></tr>
</table>
<p>Trades that would immediately violate initial margin are rejected by the
<code>_postTradeMarginOk()</code> check.</p>

<h3>Maintenance Margin</h3>
<p>Ongoing margin requirements are lower than initial margin:</p>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Position type</th><th style="text-align:left;padding:4px 8px">Maintenance</th></tr>
<tr><td style="padding:4px 8px">Short stock/bond</td><td style="padding:4px 8px">25% of notional</td></tr>
<tr><td style="padding:4px 8px">Margin debit</td><td style="padding:4px 8px">25% of negative cash</td></tr>
<tr><td style="padding:4px 8px">Short options</td><td style="padding:4px 8px">Same as initial (marked to market daily)</td></tr>
</table>

<h3>Margin Call</h3>
<p>A margin call triggers when total equity falls below the total maintenance requirement.
The simulation pauses and presents options:</p>
<ul>
<li><strong>Liquidate</strong> &mdash; auto-close positions to restore margin health</li>
<li><strong>Dismiss</strong> &mdash; continue playing at risk (further losses possible)</li>
</ul>
<p>Status indicator: <span style="color:var(--ext-green)">OK</span> &rarr;
<span style="color:var(--ext-orange)">LOW</span> &rarr;
<span style="color:var(--ext-red)">MARGIN CALL</span></p>

<h3>Equity Calculation</h3>
$$\\text{Equity} = \\text{Cash} + \\sum_{\\text{positions}} \\text{marketValue}(\\text{pos})$$
<p>Long positions contribute positive market value; short positions contribute negative
(you owe the market). Cash can be negative when buying on margin.</p>

<h3>Borrow Cost</h3>
<p>Short positions and negative cash (margin debit) incur daily interest:</p>
$$\\text{daily charge} = \\text{notional} \\times \\frac{\\max(r, 0) + k \\cdot \\sigma}{252}$$
<p>where $k$ is the borrow spread parameter and $\\sigma = \\sqrt{v}$ is instantaneous vol.
Short options do <strong>not</strong> incur borrow cost (writing options doesn&rsquo;t require
borrowing the underlying).</p>
`,
    },

    exercise: {
        title: 'Option Expiry &amp; Exercise',
        body: `
<p>American options can be exercised at any time before expiry. The simulation handles
both automatic expiry processing and manual early exercise.</p>

<h3>Automatic Exercise at Expiry</h3>
<p>At the end of the expiry day, the simulation processes all expiring options:</p>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Condition</th><th style="text-align:left;padding:4px 8px">Action</th><th style="text-align:left;padding:4px 8px">Cash effect</th></tr>
<tr><td style="padding:4px 8px">Long call, $S > K$</td><td style="padding:4px 8px">Auto-exercise</td><td style="padding:4px 8px">$+(S - K) \\times \\text{qty}$</td></tr>
<tr><td style="padding:4px 8px">Long put, $S < K$</td><td style="padding:4px 8px">Auto-exercise</td><td style="padding:4px 8px">$+(K - S) \\times \\text{qty}$</td></tr>
<tr><td style="padding:4px 8px">Long OTM</td><td style="padding:4px 8px">Expires worthless</td><td style="padding:4px 8px">$\\$0$ (premium lost)</td></tr>
<tr><td style="padding:4px 8px">Short ITM</td><td style="padding:4px 8px">Removed</td><td style="padding:4px 8px">No assignment (simplified)</td></tr>
<tr><td style="padding:4px 8px">Short OTM</td><td style="padding:4px 8px">Removed</td><td style="padding:4px 8px">Keep premium; margin released</td></tr>
</table>
<p>Settlement is cash-based &mdash; no actual share delivery. Simplified: short ITM options
are not assigned (real markets would assign them).</p>

<h3>Early Exercise</h3>
<p>Click the &ldquo;Ex&rdquo; button on any option position to exercise before expiry.
Early exercise forfeits remaining time value, so it is generally suboptimal unless:</p>
<ul>
<li><strong>Deep ITM calls before dividends</strong> &mdash; capturing the dividend may be worth more than
the remaining time value, especially when $q$ is large.</li>
<li><strong>Deep ITM puts</strong> &mdash; the interest earned on $K$ received now may exceed the remaining
time value.</li>
<li><strong>Near-zero time value</strong> &mdash; when the option is so deep ITM that time value is negligible.</li>
</ul>

<h3>Bond Maturity</h3>
<p>Zero-coupon bonds settle at face value ($\\$100$) on their maturity date.
Long bonds receive $\\$100$ per unit; short bonds pay $\\$100$ per unit.
Bond maturities are aligned with option expiry dates.</p>

<h3>The Expiry Cycle</h3>
<p>The <code>ExpiryManager</code> maintains 8 rolling expiry dates on a 63-trading-day cycle.
When an expiry passes, a new one is generated 8 cycles ahead. This means the
furthest-out expiry is approximately 2 years (504 trading days) from the current day.</p>
`,
    },

    dividends: {
        title: 'Dividend System',
        body: `
<p>The stock pays dividends controlled by the continuous yield parameter $q$.
Dividends affect the stock price, option values, and cash flow for stockholders.</p>

<h3>Continuous Yield in the SDE</h3>
<p>The dividend yield enters the stock&rsquo;s stochastic differential equation as a drag on drift:</p>
$$\\frac{dS}{S} = (\\mu - q - \\lambda k)\\,dt + \\sqrt{v}\\,dW_1 + J\\,dN(\\lambda)$$
<p>Note that $q$ does <strong>not</strong> appear in the Itô correction term ($-\\tfrac{1}{2}v$).
The continuous yield reduces the expected growth rate but does not affect the
volatility structure.</p>

<h3>Quarterly Cash Payments</h3>
<p>Every 63 trading days (aligned with the expiry cycle), a discrete cash dividend is paid:</p>
$$\\text{dividend per share} = S \\times \\frac{q}{4}$$
<ul>
<li><strong>Long stock</strong>: receives cash ($+$ to cash balance)</li>
<li><strong>Short stock</strong>: pays cash ($-$ from cash balance)</li>
<li>The stock price drops by the dividend amount on the ex-date</li>
</ul>
<p>Total net dividends are tracked in the portfolio and displayed in the Account section.</p>

<h3>Impact on Option Pricing</h3>
<p>Dividends affect options through the cost of carry $b = r - q$:</p>
<ul>
<li><strong>Higher $q$</strong> &rarr; lower forward price &rarr; calls cheaper, puts more expensive</li>
<li><strong>Early exercise of calls</strong> may be optimal just before ex-dividend dates when the dividend
exceeds the remaining time value</li>
<li>The CRR tree incorporates discrete dividends via proportional adjustment factors at
quarterly boundaries</li>
</ul>

<h3>Typical Values</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Category</th><th style="text-align:left;padding:4px 8px">Yield</th><th style="text-align:left;padding:4px 8px">Example</th></tr>
<tr><td style="padding:4px 8px">Growth stock</td><td style="padding:4px 8px">0&ndash;1%</td><td style="padding:4px 8px">Tech companies reinvesting earnings</td></tr>
<tr><td style="padding:4px 8px">Blue chip</td><td style="padding:4px 8px">2&ndash;3%</td><td style="padding:4px 8px">S&amp;P 500 average</td></tr>
<tr><td style="padding:4px 8px">High yield</td><td style="padding:4px 8px">4&ndash;5%</td><td style="padding:4px 8px">Utilities, REITs</td></tr>
</table>
`,
    },

    orderTypes: {
        title: 'Order Types',
        body: `
<p>The simulation supports three order types that determine when and how your trade executes.</p>

<h3>Market Order</h3>
<p>Executes immediately at the current bid or ask price. Buys fill at the ask; sells fill
at the bid. Market orders guarantee execution but not price &mdash; the fill price includes
the bid-ask spread as an implicit cost.</p>
<p>Use market orders when you want immediate execution and are willing to pay the spread.</p>

<h3>Limit Order</h3>
<p>Specifies a maximum buy price (or minimum sell price). The order sits in the pending
queue until the market price reaches your trigger level:</p>
<ul>
<li><strong>Buy limit</strong>: triggers when the ask $\\leq$ trigger price. Use to buy at a
lower price than the current market.</li>
<li><strong>Sell limit</strong>: triggers when the bid $\\geq$ trigger price. Use to sell at a
higher price than the current market (take profit).</li>
</ul>
<p>When triggered, the limit order executes as a market order at the prevailing bid/ask.
Limit orders may never fill if the market doesn&rsquo;t reach your price.</p>

<h3>Stop Order</h3>
<p>A stop order becomes a market order when the stock price crosses the trigger level.
Unlike limit orders, stops are used to enter <em>with</em> momentum or to cut losses:</p>
<ul>
<li><strong>Buy stop</strong>: triggers when the ask $\\geq$ trigger price. Use for breakout entries.</li>
<li><strong>Sell stop</strong>: triggers when the bid $\\leq$ trigger price. Use as a stop-loss.</li>
</ul>
<p>Warning: stop orders execute at the prevailing market price after triggering, which
may be worse than the trigger level if the price gaps through.</p>

<h3>Order Lifecycle</h3>
<p>Pending limit and stop orders are checked at every sub-step (16 per day). They appear
in the &ldquo;Pending Orders&rdquo; section of the Portfolio tab and can be cancelled via the
&ldquo;&times;&rdquo; button. Orders are cancelled automatically if their associated option expires.</p>
`,
    },

    expiry: {
        title: 'Expiry Dates &amp; DTE',
        body: `
<p>The options chain uses a rolling system of 8 expiry dates, each separated by
63 trading days (approximately one quarter).</p>

<h3>The Rolling Cycle</h3>
<p>The <code>ExpiryManager</code> initialises 8 expiries spaced at days:</p>
$$d_i = \\text{currentDay} + 63 \\times (i + 1), \\qquad i = 0, 1, \\ldots, 7$$
<p>This gives expiries from ~3 months to ~2 years out. When the nearest expiry passes,
a new one is generated 8 cycles ahead, maintaining a constant set of 8 active expiries.</p>

<h3>Days to Expiry (DTE)</h3>
<p>DTE is the number of trading days remaining until the option expires.
The dropdown shows each expiry as &ldquo;Day <em>N</em> (<em>DTE</em> DTE)&rdquo;.
Options with fewer DTE have:</p>
<ul>
<li>Faster theta decay (time value eroding more rapidly)</li>
<li>Higher gamma for ATM options (more sensitive delta)</li>
<li>Lower vega (less sensitivity to volatility)</li>
<li>Narrower effective strike range (fewer strikes worth trading)</li>
</ul>

<h3>Quarterly Alignment</h3>
<p>The 63-day expiry cycle is aligned with the quarterly dividend cycle. Dividends are
paid on expiry boundaries, which means options expiring on a dividend date incorporate
the stock price drop from the dividend payment. This alignment simplifies the
binomial tree&rsquo;s discrete dividend handling.</p>

<h3>Choosing an Expiry</h3>
<p>General guidelines:</p>
<ul>
<li><strong>Short-term (63&ndash;126 DTE)</strong>: High theta decay, good for income strategies
(selling premium). High gamma risk near expiry.</li>
<li><strong>Medium-term (189&ndash;252 DTE)</strong>: Balanced theta and vega. Typical for directional
trades and spreads.</li>
<li><strong>Long-term (315&ndash;504 DTE)</strong>: Low theta, high vega. Good for volatility bets
and LEAPS-style positions.</li>
</ul>
`,
    },

    // -----------------------------------------------------------------------
    // Strategy Topics
    // -----------------------------------------------------------------------

    strategies: {
        title: 'Strategy Builder',
        body: `
<p>The strategy builder lets you construct multi-leg option strategies by combining
calls, puts, stock, and bonds into a single package with unified execution.</p>

<h3>Building a Strategy</h3>
<ol>
<li>Switch to the <strong>Strategy tab</strong> in the sidebar.</li>
<li>Select a <strong>quantity</strong> per leg using the slider.</li>
<li>Choose an <strong>expiry</strong> from the dropdown.</li>
<li><strong>Left-click</strong> any chain cell to add a long leg; <strong>right-click</strong> for a short leg.</li>
<li>Stock and bond legs are added via the top price cells.</li>
<li>Each leg appears in the legs list below &mdash; you can remove individual legs.</li>
</ol>

<h3>Execution &amp; Rollback</h3>
<p>Click &ldquo;Execute&rdquo; to fill all legs simultaneously as a strategy group.
Each leg executes as a market order at the current bid or ask. If any leg fails
(e.g., insufficient margin for a short leg), <strong>all previously filled legs are
rolled back</strong> &mdash; positions are closed and cash is restored. This prevents
partial fills that could leave you with unintended exposure.</p>

<h3>Saved Strategies</h3>
<p>Click &ldquo;Save&rdquo; to name and store the strategy. Saved strategies appear as
grouped positions in the Portfolio tab under &ldquo;Strategy Positions.&rdquo;
Individual legs can be closed independently, but the grouping helps you
track the strategy as a whole.</p>

<h3>Payoff Diagram</h3>
<p>While in strategy mode, the left canvas shows a real-time payoff diagram.
The X-axis is the stock price at evaluation; the Y-axis is strategy P&amp;L.
Green = profit region, rose = loss region. See the Payoff reference for more details.</p>

<h3>Common Structures</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Strategy</th><th style="text-align:left;padding:4px 8px">Legs</th><th style="text-align:left;padding:4px 8px">Outlook</th></tr>
<tr><td style="padding:4px 8px">Bull call spread</td><td style="padding:4px 8px">Long call + short call (higher $K$)</td><td style="padding:4px 8px">Moderately bullish</td></tr>
<tr><td style="padding:4px 8px">Bear put spread</td><td style="padding:4px 8px">Long put + short put (lower $K$)</td><td style="padding:4px 8px">Moderately bearish</td></tr>
<tr><td style="padding:4px 8px">Straddle</td><td style="padding:4px 8px">Long call + long put (same $K$)</td><td style="padding:4px 8px">Expecting big move, direction unknown</td></tr>
<tr><td style="padding:4px 8px">Strangle</td><td style="padding:4px 8px">Long OTM call + long OTM put</td><td style="padding:4px 8px">Same as straddle, cheaper entry</td></tr>
<tr><td style="padding:4px 8px">Iron condor</td><td style="padding:4px 8px">Short strangle + protective long wings</td><td style="padding:4px 8px">Range-bound; collecting premium</td></tr>
<tr><td style="padding:4px 8px">Butterfly</td><td style="padding:4px 8px">1 long + 2 short + 1 long at 3 strikes</td><td style="padding:4px 8px">Pinning to a target price</td></tr>
<tr><td style="padding:4px 8px">Covered call</td><td style="padding:4px 8px">Long stock + short OTM call</td><td style="padding:4px 8px">Income; willing to sell at $K$</td></tr>
<tr><td style="padding:4px 8px">Protective put</td><td style="padding:4px 8px">Long stock + long OTM put</td><td style="padding:4px 8px">Bullish with downside protection</td></tr>
</table>
`,
    },

    payoff: {
        title: 'Payoff Diagrams',
        body: `
<p>The payoff diagram shows the P&amp;L profile of the current strategy across a range
of possible stock prices. It updates in real time as you add or remove legs.</p>

<h3>Reading the Diagram</h3>
<ul>
<li><strong>X-axis</strong>: stock price at evaluation time</li>
<li><strong>Y-axis</strong>: strategy P&amp;L (profit/loss in dollars)</li>
<li><strong>Green region</strong>: profit (above the zero line)</li>
<li><strong>Rose region</strong>: loss (below the zero line)</li>
<li><strong>Zero line</strong>: breakeven &mdash; no profit, no loss</li>
<li><strong>Vertical dashed line</strong>: current stock price</li>
</ul>

<h3>Time-to-Expiry Slider</h3>
<p>The slider at the bottom adjusts the evaluation time between now and the nearest
expiry. At the leftmost position (0%), the diagram shows the payoff at expiry &mdash;
the characteristic hockey-stick shape of raw option payoffs. As you slide right
toward 100% (now), the lines smooth out due to remaining time value.</p>
<p>The slider percentage maps to an evaluation day:
$\\text{evalDay} = \\text{currentDay} + \\text{pct} \\times \\text{maxDTE}$,
clamped to the range of active leg expiries.</p>

<h3>Greek Overlays</h3>
<p>Click the legend entries ($\\Delta$, $\\Gamma$, $\\Theta$, $\\mathcal{V}$, $\\rho$) to
overlay Greek profiles across the strike range. Each Greek has its own Y-axis scale.
The overlays show how risk sensitivities change with the stock price, helping you
understand where your exposures concentrate.</p>
<p>Key patterns to observe:</p>
<ul>
<li>Delta crosses zero at the breakeven(s) of simple spreads</li>
<li>Gamma peaks at each leg&rsquo;s strike</li>
<li>Theta is most negative where gamma is highest</li>
<li>Vega has a broad hump centered on ATM strikes</li>
</ul>

<h3>Breakeven Points</h3>
<p>Dots on the zero line mark prices where the strategy crosses from profit to loss
(or vice versa). The summary panel lists exact breakeven values. Breakevens shift
as the slider moves &mdash; an initially unprofitable position may become profitable
if the stock reaches certain levels before expiry.</p>

<h3>Caching</h3>
<p>The diagram uses input-keyed caching: each combination of legs, time, and stock price
range is computed once and reused until inputs change. Greek overlays are computed
lazily and cached independently per Greek.</p>
`,
    },

    // -----------------------------------------------------------------------
    // Simulation Parameters
    // -----------------------------------------------------------------------

    mu: {
        title: 'Drift ($\\mu$)',
        body: `
<p>The expected annualised return of the underlying stock. This is the &ldquo;real-world&rdquo;
drift &mdash; the average rate at which the stock price grows before accounting for
dividends and jumps.</p>

<h3>Role in the SDE</h3>
<p>Drift enters the GBM equation as part of the deterministic trend:</p>
$$\\frac{dS}{S} = (\\mu - q - \\lambda k - \\tfrac{1}{2}v)\\,dt + \\cdots$$
<p>The effective drift is $\\mu$ minus the dividend yield ($q$), the jump compensator
($\\lambda k$), and the Itô correction ($\\tfrac{1}{2}v$). When $\\mu = 0.08$ and other
adjustments total ~0.04, the stock grows at roughly 4% per year on average.</p>

<h3>Risk-Neutral vs. Real-World</h3>
<p>Option pricing uses the risk-neutral drift $r$ (not $\\mu$) &mdash; the cost of carry
determines option values. But the stock <em>simulation</em> uses $\\mu$ as the physical drift,
so changing $\\mu$ affects the stock&rsquo;s direction without directly changing option pricing.
The difference $\\mu - r$ is the equity risk premium.</p>

<h3>Typical Values</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Regime</th><th style="text-align:left;padding:4px 8px">$\\mu$</th><th style="text-align:left;padding:4px 8px">Character</th></tr>
<tr><td style="padding:4px 8px">Strong bull</td><td style="padding:4px 8px">0.15&ndash;0.30</td><td style="padding:4px 8px">Persistent uptrend</td></tr>
<tr><td style="padding:4px 8px">Normal</td><td style="padding:4px 8px">0.05&ndash;0.10</td><td style="padding:4px 8px">Historical equity average</td></tr>
<tr><td style="padding:4px 8px">Sideways</td><td style="padding:4px 8px">0.00&ndash;0.02</td><td style="padding:4px 8px">Range-bound market</td></tr>
<tr><td style="padding:4px 8px">Bear/crisis</td><td style="padding:4px 8px">$-0.10$ to $-0.30$</td><td style="padding:4px 8px">Sustained decline</td></tr>
</table>
<p>Range: $-0.50$ to $+0.50$.</p>
`,
    },

    theta: {
        title: 'Vol Mean ($\\theta$)',
        body: `
<p>The long-run variance level in the Heston model. Volatility reverts toward
$\\sqrt{\\theta}$ over time, making $\\theta$ the &ldquo;equilibrium&rdquo; of the vol process.</p>

<h3>Role in the Heston SDE</h3>
$$dv = \\kappa(\\theta - v)\\,dt + \\xi\\sqrt{v}\\,dW_2$$
<p>When $v > \\theta$, the drift term $\\kappa(\\theta - v)$ is negative, pulling variance down.
When $v < \\theta$, the drift is positive, pushing variance up. The speed of this
reversion is controlled by $\\kappa$.</p>

<h3>Interpretation</h3>
<p>$\\theta$ is a variance (not a volatility), so the implied annualised vol is $\\sqrt{\\theta}$:</p>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">$\\theta$</th><th style="text-align:left;padding:4px 8px">$\\sqrt{\\theta}$</th><th style="text-align:left;padding:4px 8px">Character</th></tr>
<tr><td style="padding:4px 8px">0.01</td><td style="padding:4px 8px">10%</td><td style="padding:4px 8px">Very calm (money market)</td></tr>
<tr><td style="padding:4px 8px">0.04</td><td style="padding:4px 8px">20%</td><td style="padding:4px 8px">Typical equity</td></tr>
<tr><td style="padding:4px 8px">0.09</td><td style="padding:4px 8px">30%</td><td style="padding:4px 8px">Elevated volatility</td></tr>
<tr><td style="padding:4px 8px">0.25</td><td style="padding:4px 8px">50%</td><td style="padding:4px 8px">Crisis-level</td></tr>
</table>

<h3>Effect on Options</h3>
<p>Higher $\\theta$ raises the baseline vol used for long-dated option pricing (via
<code>computeEffectiveSigma</code>), making all options more expensive. Short-dated options
may still be priced near $\\sqrt{v}$ if $\\kappa$ is low, but long-dated options converge
to $\\sqrt{\\theta}$.</p>

<h3>Feller Condition</h3>
<p>$\\theta$ appears in the Feller condition $2\\kappa\\theta > \\xi^2$. For a given $\\kappa$ and $\\xi$,
there is a minimum $\\theta$ that keeps variance strictly positive.</p>

<p>Range: 0.005 to 1.00.</p>
`,
    },

    kappa: {
        title: 'Mean Reversion ($\\kappa$)',
        body: `
<p>The speed at which the Heston variance process reverts to its long-run level $\\theta$.
Higher $\\kappa$ means volatility snaps back to equilibrium faster after shocks.</p>

<h3>Role in the Heston SDE</h3>
$$dv = \\kappa(\\theta - v)\\,dt + \\xi\\sqrt{v}\\,dW_2$$
<p>The half-life of a variance deviation is $\\ln(2)/\\kappa$. With $\\kappa = 3$, a vol shock
has a half-life of ~0.23 years (~58 trading days). With $\\kappa = 0.5$, the half-life
is ~1.4 years (~350 days).</p>

<h3>Effect on Option Pricing</h3>
<p>$\\kappa$ shapes the term structure of volatility:</p>
<ul>
<li><strong>High $\\kappa$</strong>: Long-dated vols converge quickly to $\\sqrt{\\theta}$, creating a flat
term structure.</li>
<li><strong>Low $\\kappa$</strong>: Current vol persists into the future, so if $v > \\theta$, long-dated
options remain expensive. This steepens (or inverts) the vol term structure.</li>
</ul>

<h3>Feller Condition</h3>
$$2\\kappa\\theta > \\xi^2$$
<p>For given $\\theta$ and $\\xi$, there is a minimum $\\kappa$ that prevents the variance
process from hitting zero. When violated, the full truncation scheme floors $v$ at $0$.</p>

<h3>Typical Values</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">$\\kappa$</th><th style="text-align:left;padding:4px 8px">Half-life</th><th style="text-align:left;padding:4px 8px">Character</th></tr>
<tr><td style="padding:4px 8px">0.5</td><td style="padding:4px 8px">~1.4 years</td><td style="padding:4px 8px">Persistent vol regimes</td></tr>
<tr><td style="padding:4px 8px">2.0</td><td style="padding:4px 8px">~0.35 years</td><td style="padding:4px 8px">Moderate; typical equity</td></tr>
<tr><td style="padding:4px 8px">5.0</td><td style="padding:4px 8px">~0.14 years</td><td style="padding:4px 8px">Fast reversion; transient spikes</td></tr>
</table>
<p>Range: 0.05 to 10.</p>
`,
    },

    xi: {
        title: 'Vol of Vol ($\\xi$)',
        body: `
<p>The volatility of the variance process in the Heston model. Controls how erratically
volatility itself swings around its mean-reverting path.</p>

<h3>Role in the Heston SDE</h3>
$$dv = \\kappa(\\theta - v)\\,dt + \\xi\\sqrt{v}\\,dW_2$$
<p>The $\\xi\\sqrt{v}$ term is the diffusion of variance. Higher $\\xi$ means variance
can deviate further from $\\theta$ on each step, creating more dramatic volatility
regime changes.</p>

<h3>Effect on the Volatility Surface</h3>
<ul>
<li><strong>Skew</strong>: $\\xi$ interacts with $\\rho$ to produce the first-order skew:
$d\\sigma/d(\\ln K) \\approx \\rho\\xi/(2\\sigma)$. Higher $\\xi$ steepens the skew.</li>
<li><strong>Smile curvature</strong>: The second-order term $\\xi^2/(12\\sigma^2)$ lifts both wings
of the volatility smile symmetrically.</li>
<li><strong>Convexity correction</strong>: Higher $\\xi$ raises the ATM vol level via the Gatheral
convexity adjustment.</li>
</ul>

<h3>Interaction with $\\kappa$</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">$\\kappa$</th><th style="text-align:left;padding:4px 8px">$\\xi$</th><th style="text-align:left;padding:4px 8px">Behaviour</th></tr>
<tr><td style="padding:4px 8px">High</td><td style="padding:4px 8px">Low</td><td style="padding:4px 8px">Calm: vol stays near $\\theta$, shallow smile</td></tr>
<tr><td style="padding:4px 8px">High</td><td style="padding:4px 8px">High</td><td style="padding:4px 8px">Spiky but transient vol shocks</td></tr>
<tr><td style="padding:4px 8px">Low</td><td style="padding:4px 8px">High</td><td style="padding:4px 8px">Crisis: wild, persistent vol swings</td></tr>
</table>

<h3>Fat Tails</h3>
<p>When $\\xi > 0$, the return distribution has heavier tails than log-normal. The
excess kurtosis increases with $\\xi$, meaning extreme returns (both positive and
negative) are more likely than a constant-vol model would predict.</p>

<h3>Typical Values</h3>
<p>Moderate: 0.2&ndash;0.5. High: 0.6&ndash;1.0. Range: 0.05 to 1.50.</p>
`,
    },

    rho: {
        title: 'Correlation ($\\rho$)',
        body: `
<p>Correlation between the stock price and variance Brownian motions
($\\rho = \\text{Corr}(dW_1, dW_2)$). This single parameter controls the asymmetry
of the volatility smile.</p>

<h3>The Leverage Effect</h3>
<p>When $\\rho < 0$ (the norm for equities), stock price drops coincide with variance
increases. This is called the &ldquo;leverage effect&rdquo;: as a company&rsquo;s equity value falls,
its debt-to-equity ratio rises, increasing financial risk and perceived volatility.</p>

<h3>Impact on the Skew</h3>
<p>The first-order ATM implied volatility skew is approximately:</p>
$$\\frac{\\partial\\sigma_{\\text{imp}}}{\\partial\\ln K}\\bigg|_{K=S}
\\approx \\frac{\\rho\\xi}{2\\sigma} \\cdot \\frac{1 - e^{-\\kappa T}}{\\kappa T}$$
<ul>
<li><strong>$\\rho < 0$</strong>: OTM puts get higher implied vol than OTM calls (downward skew).
This is the typical equity pattern &mdash; put protection is expensive.</li>
<li><strong>$\\rho \\approx 0$</strong>: The smile is symmetric. OTM puts and calls have similar vol.</li>
<li><strong>$\\rho > 0$</strong>: Inverted skew &mdash; OTM calls are more expensive. Rare for equities,
sometimes seen in commodities.</li>
</ul>

<h3>Cholesky Decomposition</h3>
<p>The correlated noise is generated via:</p>
$$Z_1 = \\epsilon_1, \\qquad Z_2 = \\rho\\,\\epsilon_1 + \\sqrt{1 - \\rho^2}\\,\\epsilon_2$$
<p>This ensures $\\text{Corr}(Z_1, Z_2) = \\rho$ while keeping $Z_2$ properly normalised.
The interest rate process $Z_3$ is independent of both.</p>

<h3>Typical Values</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">$\\rho$</th><th style="text-align:left;padding:4px 8px">Character</th></tr>
<tr><td style="padding:4px 8px">$-0.85$</td><td style="padding:4px 8px">Extreme leverage effect; very steep skew</td></tr>
<tr><td style="padding:4px 8px">$-0.50$</td><td style="padding:4px 8px">Typical equity</td></tr>
<tr><td style="padding:4px 8px">$0.00$</td><td style="padding:4px 8px">Symmetric smile; no leverage effect</td></tr>
<tr><td style="padding:4px 8px">$+0.30$</td><td style="padding:4px 8px">Inverted skew (some commodities)</td></tr>
</table>
<p>Range: $-0.99$ to $+0.50$.</p>
`,
    },

    lambda: {
        title: 'Jump Rate ($\\lambda$)',
        body: `
<p>The expected number of price jumps per year, modelled as a Poisson process with
intensity $\\lambda$. Jumps introduce sudden, discontinuous price changes beyond what
the diffusion component can produce.</p>

<h3>Poisson Process</h3>
<p>In a small interval $dt$, the probability of exactly one jump is $\\lambda\\,dt$, and
the probability of zero jumps is $1 - \\lambda\\,dt$ (to first order). Over one year,
the expected number of jumps is $\\lambda$. The inter-jump time is exponentially
distributed with mean $1/\\lambda$.</p>

<h3>Jump Compensation</h3>
<p>To prevent jumps from biasing the expected return, the drift includes a compensator:</p>
$$-\\lambda k, \\qquad k = E[e^J - 1] = e^{\\mu_J + \\sigma_J^2/2} - 1$$
<p>This ensures $E[dS/S]$ under the physical measure equals
$(\\mu - q)\\,dt$ regardless of jump parameters.</p>

<h3>Effect on Returns</h3>
<ul>
<li>$\\lambda = 0$: Pure diffusion; smooth price paths</li>
<li>$\\lambda = 0.5$: ~1 jump every 2 years; occasional gaps</li>
<li>$\\lambda = 3$: ~3 jumps/year; frequent sudden moves</li>
<li>$\\lambda = 8$+: Crisis regime; highly discontinuous paths</li>
</ul>

<h3>Impact on Options</h3>
<p>Jumps fatten the tails of the return distribution, making deep OTM options more
valuable than Black-Scholes predicts. The combination of jumps and stochastic vol
can produce realistic volatility surfaces with steep skew and excess kurtosis.</p>

<p>Range: 0 to 15.</p>
`,
    },

    muJ: {
        title: 'Jump Mean ($\\mu_J$)',
        body: `
<p>The average size of log-price jumps. Controls whether jumps tend to push the
stock price up or down.</p>

<h3>Jump Distribution</h3>
<p>Each jump size $J$ is drawn from a log-normal distribution:</p>
$$\\ln(1 + J) \\sim \\mathcal{N}(\\mu_J,\\, \\sigma_J^2)$$
<p>The actual multiplicative price change from a jump is $e^{\\mu_J + \\sigma_J Z}$
where $Z \\sim \\mathcal{N}(0,1)$. With $\\mu_J = -0.05$ and $\\sigma_J = 0.03$,
a typical jump drops the stock by roughly 5%.</p>

<h3>Asymmetry</h3>
<ul>
<li><strong>Negative $\\mu_J$</strong> (default): Jumps tend to be downward, modelling crash risk.
This is the dominant pattern in equity markets &mdash; large sudden drops (flash crashes,
panic selling) are more common than large sudden rises.</li>
<li><strong>Positive $\\mu_J$</strong>: Upward jumps. Rare for equities but can model
positive news shocks or short squeezes.</li>
<li><strong>$\\mu_J = 0$</strong>: Symmetric jumps &mdash; equally likely up or down.</li>
</ul>

<h3>Interaction with Skew</h3>
<p>Negative $\\mu_J$ contributes to the leftward skew of the return distribution,
complementing the Heston $\\rho$ effect. Both mechanisms make OTM puts more
valuable (reflecting crash protection demand).</p>

<h3>Typical Values</h3>
<p>Mild: $-0.01$ to $-0.03$. Severe crash: $-0.08$ to $-0.15$.
Range: $-0.25$ to $+0.15$.</p>
`,
    },

    sigmaJ: {
        title: 'Jump Vol ($\\sigma_J$)',
        body: `
<p>Standard deviation of jump sizes. Controls how variable individual jumps are &mdash;
whether jumps are consistently similar or wildly different each time.</p>

<h3>Effect on Tails</h3>
<p>Higher $\\sigma_J$ means some jumps are small while others are catastrophic. The
jump size distribution $\\ln(1+J) \\sim \\mathcal{N}(\\mu_J, \\sigma_J^2)$ has variance
$\\sigma_J^2$. This directly increases the kurtosis of the return distribution:</p>
$$\\text{excess kurtosis from jumps} \\propto \\lambda\\,(\\mu_J^4 + 6\\mu_J^2\\sigma_J^2 + 3\\sigma_J^4)$$
<p>Even a small increase in $\\sigma_J$ significantly fattens the tails because it enters
as the fourth power.</p>

<h3>Interaction with $\\mu_J$</h3>
<p>The worst-case scenario combines negative $\\mu_J$ (downward jumps on average) with
high $\\sigma_J$ (unpredictable jump magnitudes). This creates a &ldquo;fat left tail&rdquo;
where catastrophic crashes are both frequent and variable in severity.</p>

<h3>Impact on Options</h3>
<p>High $\\sigma_J$ inflates the prices of deep OTM options on both sides, as the
probability of extreme moves increases. This manifests as wider &ldquo;wings&rdquo; in the
volatility smile.</p>

<h3>Typical Values</h3>
<p>Moderate: 0.03&ndash;0.06. High: 0.08&ndash;0.15. Range: 0.005 to 0.25.</p>
`,
    },

    a: {
        title: 'Rate Reversion ($a$)',
        body: `
<p>The mean-reversion speed of the Vasicek interest rate process. Controls how
persistently rates deviate from their equilibrium level $b$.</p>

<h3>Role in the Vasicek SDE</h3>
$$dr = a(b - r)\\,dt + \\sigma_R\\,dW_3$$
<p>The rate is pulled toward $b$ with force proportional to the deviation. The half-life
of a rate shock is $\\ln(2)/a$:</p>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">$a$</th><th style="text-align:left;padding:4px 8px">Half-life</th><th style="text-align:left;padding:4px 8px">Character</th></tr>
<tr><td style="padding:4px 8px">0.1</td><td style="padding:4px 8px">~6.9 years</td><td style="padding:4px 8px">Very persistent rate changes</td></tr>
<tr><td style="padding:4px 8px">0.5</td><td style="padding:4px 8px">~1.4 years</td><td style="padding:4px 8px">Moderate persistence</td></tr>
<tr><td style="padding:4px 8px">1.0</td><td style="padding:4px 8px">~0.7 years</td><td style="padding:4px 8px">Fairly quick reversion</td></tr>
<tr><td style="padding:4px 8px">2.0</td><td style="padding:4px 8px">~0.35 years</td><td style="padding:4px 8px">Transient rate shocks</td></tr>
</table>

<h3>Effect on Bonds</h3>
<p>Fast reversion ($a$ large) means rate shocks are short-lived, so bond prices recover
quickly. Slow reversion means rate moves persist, creating larger bond P&amp;L swings.
Bond duration is capped at $1/a$: $D = B(T) = (1 - e^{-aT})/a \\leq 1/a$.</p>

<h3>Effect on Options</h3>
<p>Rate reversion affects option rho through the per-step Vasicek discounting in the
binomial tree. Faster reversion means rate shocks fade before long-dated options expire,
reducing their rho exposure.</p>

<p>Range: 0.01 to 2.0.</p>
`,
    },

    b: {
        title: 'Rate Mean ($b$)',
        body: `
<p>The long-run equilibrium level for the risk-free interest rate. Rates revert toward
$b$ over time under the Vasicek model.</p>

<h3>Effect on Markets</h3>
<p>$b$ sets the baseline around which rates fluctuate:</p>
<ul>
<li><strong>Options</strong>: Higher $b$ increases the risk-neutral drift ($r - q$), raising call
values and lowering put values over the long run.</li>
<li><strong>Bonds</strong>: Higher $b$ means rates revert to a higher level, depressing long-term
bond prices. Bond prices and rates move inversely: $P \\propto e^{-rT}$.</li>
<li><strong>Borrow cost</strong>: The borrow cost formula uses $\\max(r, 0)$, so higher equilibrium
rates increase the cost of short positions and margin debit.</li>
</ul>

<h3>Typical Values</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Environment</th><th style="text-align:left;padding:4px 8px">$b$</th></tr>
<tr><td style="padding:4px 8px">Zero-rate environment</td><td style="padding:4px 8px">0&ndash;1%</td></tr>
<tr><td style="padding:4px 8px">Normal</td><td style="padding:4px 8px">3&ndash;5%</td></tr>
<tr><td style="padding:4px 8px">Rate hike cycle</td><td style="padding:4px 8px">6&ndash;8%</td></tr>
<tr><td style="padding:4px 8px">Negative rate (Vasicek allows this)</td><td style="padding:4px 8px">$< 0$</td></tr>
</table>
<p>Range: $-5\\%$ to $+20\\%$.</p>
`,
    },

    sigmaR: {
        title: 'Rate Vol ($\\sigma_R$)',
        body: `
<p>Volatility of the Vasicek interest rate process. Controls the magnitude of random
rate fluctuations around the mean-reverting path $b$.</p>

<h3>Role in the Vasicek SDE</h3>
$$dr = a(b - r)\\,dt + \\sigma_R\\,dW_3$$
<p>The stationary variance of the rate process is $\\sigma_R^2 / (2a)$, so the long-run
standard deviation of rates is $\\sigma_R / \\sqrt{2a}$.</p>

<h3>Effect on Bonds</h3>
<p>Higher $\\sigma_R$ creates wider rate swings, directly increasing bond price volatility.
For a zero-coupon bond with duration $B(T)$, the approximate price volatility is:</p>
$$\\sigma_{\\text{bond}} \\approx B(T) \\times P \\times \\sigma_R$$
<p>Longer-maturity bonds amplify rate vol via the duration multiplier.</p>

<h3>Probability of Negative Rates</h3>
<p>The stationary distribution of the Vasicek process is $r \\sim \\mathcal{N}(b, \\sigma_R^2/(2a))$.
The probability of $r < 0$ is:</p>
$$P(r < 0) = \\Phi\\!\\left(\\frac{-b}{\\sigma_R/\\sqrt{2a}}\\right)$$
<p>With $b = 4\\%, \\sigma_R = 1\\%, a = 0.5$: $P(r < 0) \\approx 0.2\\%$. With $\\sigma_R = 2\\%$:
$P(r < 0) \\approx 2.3\\%$.</p>

<h3>Typical Values</h3>
<p>Normal: 0.005&ndash;0.010. Volatile: 0.012&ndash;0.020. Range: 0.001 to 0.050.</p>
`,
    },

    borrowSpread: {
        title: 'Borrow Spread ($k$)',
        body: `
<p>Volatility scaling factor in the borrow cost formula. Higher $k$ makes it more
expensive to maintain short positions and margin debit.</p>

<h3>Cost Formula</h3>
$$\\text{daily charge} = \\text{notional} \\times \\frac{\\max(r,\\, 0) + k \\cdot \\sigma}{252}$$
<p>The borrow cost has two components:</p>
<ul>
<li><strong>Risk-free rate floor</strong>: $\\max(r, 0)$ ensures the base rate is non-negative</li>
<li><strong>Volatility-scaled spread</strong>: $k \\cdot \\sigma$ adds a premium proportional to
current instantaneous volatility. This models the real-world dynamic where
hard-to-borrow, volatile stocks command higher borrow fees.</li>
</ul>

<h3>Affected Positions</h3>
<ul>
<li><strong>Short stock</strong>: borrow cost on the full notional ($|\\text{qty}| \\times S$)</li>
<li><strong>Short bonds</strong>: borrow cost on the full notional ($|\\text{qty}| \\times P_{\\text{bond}}$)</li>
<li><strong>Negative cash</strong> (margin debit): interest on the debit balance</li>
<li><strong>Short options</strong>: <strong>no</strong> borrow cost (writing doesn&rsquo;t require borrowing)</li>
</ul>

<h3>Event Shocks</h3>
<p>Dynamic regime events (like short squeezes) can spike the borrow spread,
dramatically increasing the cost of short positions. A borrow spread of $k = 3$
with 30% vol and 4% rate gives a daily charge of
$(0.04 + 3 \\times 0.30)/252 \\approx 0.38\\%$ of notional per day.</p>

<h3>Typical Values</h3>
<p>Normal: 0.5. Elevated: 1&ndash;2. Squeeze: 3&ndash;5. Range: 0 to 5.</p>
`,
    },

    q: {
        title: 'Dividend Yield ($q$)',
        body: `
<p>Continuous dividend yield applied to the stock. Controls both the stock drift
and the quarterly cash dividend payments.</p>

<h3>Effect on Drift</h3>
<p>The dividend yield reduces the stock&rsquo;s growth rate in the SDE:</p>
$$\\frac{dS}{S} = (\\mu - q - \\lambda k - \\tfrac{1}{2}v)\\,dt + \\cdots$$
<p>A higher $q$ means more value is extracted as dividends, leaving less for
capital appreciation.</p>

<h3>Effect on Option Pricing</h3>
<p>The cost of carry $b = r - q$ enters option pricing through the forward price.
Higher $q$:</p>
<ul>
<li>Reduces the forward $F = S \\cdot e^{(r-q)T}$ &rarr; calls cheaper, puts dearer</li>
<li>Makes early exercise of calls more likely (capturing dividends)</li>
<li>Enters the binomial tree via proportional adjustments at quarterly boundaries</li>
</ul>

<h3>Cash Payments</h3>
<p>Every 63 trading days: $\\text{DPS} = S \\times q/4$. Long stock receives,
short stock pays. Tracked in the Account section as &ldquo;Dividends.&rdquo;</p>

<h3>Typical Values</h3>
<p>Growth stocks: 0&ndash;1%. Blue chips: 2&ndash;3%. High yield: 4&ndash;5%. Range: 0% to 10%.</p>
`,
    },

    // -----------------------------------------------------------------------
    // Portfolio / Account
    // -----------------------------------------------------------------------

    cash: {
        title: 'Cash Balance',
        body: `
<p>Your available cash balance. Cash changes with every trade, dividend payment,
borrow cost deduction, and option exercise.</p>

<h3>How Cash Changes</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Event</th><th style="text-align:left;padding:4px 8px">Cash effect</th></tr>
<tr><td style="padding:4px 8px">Buy stock/bond/option</td><td style="padding:4px 8px">$-$ (pay ask price $\\times$ qty)</td></tr>
<tr><td style="padding:4px 8px">Sell/short stock/bond/option</td><td style="padding:4px 8px">$+$ (receive bid price $\\times$ qty)</td></tr>
<tr><td style="padding:4px 8px">Close position</td><td style="padding:4px 8px">Reverse of the entry (at current bid/ask)</td></tr>
<tr><td style="padding:4px 8px">Dividend (long stock)</td><td style="padding:4px 8px">$+S \\times q/4 \\times \\text{qty}$</td></tr>
<tr><td style="padding:4px 8px">Dividend (short stock)</td><td style="padding:4px 8px">$-S \\times q/4 \\times |\\text{qty}|$</td></tr>
<tr><td style="padding:4px 8px">Borrow cost (daily)</td><td style="padding:4px 8px">$-$ deducted each trading day</td></tr>
<tr><td style="padding:4px 8px">Option exercise (ITM call)</td><td style="padding:4px 8px">$+(S - K) \\times \\text{qty}$</td></tr>
<tr><td style="padding:4px 8px">Bond maturity (long)</td><td style="padding:4px 8px">$+\\$100 \\times \\text{qty}$</td></tr>
</table>

<h3>Negative Cash (Margin)</h3>
<p>Cash can go negative when you buy on margin. Negative cash incurs daily interest
via the borrow cost formula. Your equity must stay above the maintenance margin
requirement, or a margin call is triggered.</p>

<h3>Starting Capital</h3>
<p>The simulation starts with $\\$10{,}000$ in cash. This resets on preset change.</p>
`,
    },

    portfolioValue: {
        title: 'Portfolio Value',
        body: `
<p>Total equity: cash plus the mark-to-market value of all open positions.</p>

<h3>Calculation</h3>
$$\\text{Portfolio Value} = \\text{Cash} + \\sum_{i} \\text{marketValue}(\\text{pos}_i)$$
<p>Where the market value of each position is:</p>
<ul>
<li><strong>Long stock</strong>: $\\text{qty} \\times S$ (current stock price)</li>
<li><strong>Short stock</strong>: $\\text{qty} \\times S$ (negative qty, so negative value)</li>
<li><strong>Long option</strong>: $\\text{qty} \\times V(S, K, T, r, \\sigma)$ (option model price)</li>
<li><strong>Short option</strong>: $\\text{qty} \\times V$ (negative qty = liability)</li>
<li><strong>Long bond</strong>: $\\text{qty} \\times P_{\\text{bond}}(r, T)$</li>
<li><strong>Short bond</strong>: $\\text{qty} \\times P_{\\text{bond}}$ (negative)</li>
</ul>
<p>Portfolio value uses <strong>mid-prices</strong> (theoretical fair value), not bid/ask.
Liquidation would realise less due to spreads.</p>

<h3>Tracking</h3>
<p>The simulation tracks peak portfolio value and maximum drawdown
($\\max(1 - \\text{value}/\\text{peak})$) for the epilogue scorecard.</p>
`,
    },

    totalPnl: {
        title: 'Total P&amp;L',
        body: `
<p>Your total profit or loss since the simulation started.</p>

<h3>Calculation</h3>
$$\\text{Total P\\&L} = \\text{Portfolio Value} - \\text{Initial Capital}$$
<p>This is an all-in measure that includes:</p>
<ul>
<li>Realised P&amp;L from closed trades</li>
<li>Unrealised P&amp;L from open positions (mark-to-market)</li>
<li>Dividends received or paid</li>
<li>Borrow costs deducted</li>
<li>Spread costs (embedded in fill prices)</li>
</ul>

<h3>Colour Coding</h3>
<p>Positive P&amp;L is displayed in <span style="color:var(--ext-green)">green</span>;
negative in <span style="color:var(--ext-rose)">rose</span>. The colour updates
in real time as market prices change.</p>
`,
    },

    borrowCost: {
        title: 'Borrow Cost',
        body: `
<p>Cumulative interest charged on short positions and margin debit (negative cash).
This is a pure cost that reduces your portfolio value over time.</p>

<h3>Daily Calculation</h3>
$$\\text{daily cost} = \\sum_{\\text{shorts}} \\text{notional}_i
\\times \\frac{\\max(r, 0) + k\\sigma}{252}$$
<p>Applied once per trading day to:</p>
<ul>
<li>Short stock positions (notional = $|\\text{qty}| \\times S$)</li>
<li>Short bond positions (notional = $|\\text{qty}| \\times P_{\\text{bond}}$)</li>
<li>Negative cash balance (margin debit interest)</li>
</ul>
<p>Short <strong>options</strong> do not incur borrow cost.</p>

<h3>The Cost Components</h3>
<ul>
<li><strong>$\\max(r, 0)$</strong>: base risk-free rate (floored at zero)</li>
<li><strong>$k \\cdot \\sigma$</strong>: volatility-scaled spread. In high-vol environments,
borrow becomes expensive rapidly.</li>
</ul>

<h3>Accumulation</h3>
<p>The displayed value is the total cumulative borrow cost since the simulation started.
Individual position borrow costs are tracked and reported on the epilogue scorecard.</p>
`,
    },

    // -----------------------------------------------------------------------
    // Settings / Regime
    // -----------------------------------------------------------------------

    regime: {
        title: 'Market Regime',
        body: `
<p>Presets that configure all simulation parameters at once, creating different
market environments. Changing the preset resets the simulation and portfolio.</p>

<h3>Static Presets</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Preset</th><th style="text-align:left;padding:4px 8px">$\\mu$</th><th style="text-align:left;padding:4px 8px">$\\theta$</th><th style="text-align:left;padding:4px 8px">$\\lambda$</th><th style="text-align:left;padding:4px 8px">$b$</th><th style="text-align:left;padding:4px 8px">Character</th></tr>
<tr><td style="padding:4px 8px">Calm Bull</td><td style="padding:4px 8px">0.08</td><td style="padding:4px 8px">0.04</td><td style="padding:4px 8px">0.5</td><td style="padding:4px 8px">4%</td><td style="padding:4px 8px">Steady uptrend, low vol</td></tr>
<tr><td style="padding:4px 8px">Sideways</td><td style="padding:4px 8px">0.02</td><td style="padding:4px 8px">0.06</td><td style="padding:4px 8px">1.0</td><td style="padding:4px 8px">3%</td><td style="padding:4px 8px">Range-bound, moderate vol</td></tr>
<tr><td style="padding:4px 8px">Volatile</td><td style="padding:4px 8px">0.05</td><td style="padding:4px 8px">0.12</td><td style="padding:4px 8px">3.0</td><td style="padding:4px 8px">4%</td><td style="padding:4px 8px">Big swings, frequent jumps</td></tr>
<tr><td style="padding:4px 8px">Crisis</td><td style="padding:4px 8px">$-0.15$</td><td style="padding:4px 8px">0.25</td><td style="padding:4px 8px">8.0</td><td style="padding:4px 8px">1%</td><td style="padding:4px 8px">Bear market, extreme vol</td></tr>
<tr><td style="padding:4px 8px">Rate Hike</td><td style="padding:4px 8px">0.04</td><td style="padding:4px 8px">0.06</td><td style="padding:4px 8px">1.0</td><td style="padding:4px 8px">8%</td><td style="padding:4px 8px">High rates, moderate vol</td></tr>
</table>

<h3>Dynamic Presets</h3>
<p>The two dynamic presets add a narrative event engine:</p>
<ul>
<li><strong>Dynamic (Offline)</strong>: draws from 88 curated events via weighted random selection.
Events shift simulation parameters, creating evolving market conditions.</li>
<li><strong>Dynamic (LLM)</strong>: uses the Claude API to generate contextual events based on
the simulation&rsquo;s current state and narrative history. Requires an API key.</li>
</ul>
<p>In dynamic mode, parameters change over time as events fire &mdash; the initial preset
values are just the starting point.</p>

<h3>Advanced Parameters</h3>
<p>Click &ldquo;Advanced Parameters&rdquo; to manually adjust individual model parameters.
Changes take effect immediately but will be overwritten if you switch presets.</p>
`,
    },

    riskFreeRate: {
        title: 'Risk-Free Rate',
        body: `
<p>The current instantaneous risk-free interest rate $r$, evolving under the
Vasicek model. This is the rate used for option pricing, bond valuation,
and borrow cost calculations.</p>

<h3>How It Moves</h3>
$$dr = a(b - r)\\,dt + \\sigma_R\\,dW_3$$
<p>The rate is updated at every sub-step (16 per day) and displayed as an annualised
percentage. The sparkline chart below shows the rate&rsquo;s recent history.</p>

<h3>Impact on Instruments</h3>
<ul>
<li><strong>Options</strong>: Higher $r$ increases call values and decreases put values (via
the forward price $F = Se^{(r-q)T}$). The binomial tree uses per-step Vasicek
rates, so the full rate path is incorporated.</li>
<li><strong>Bonds</strong>: Price is $100 \\cdot e^{-rT}$, so rate increases decrease bond prices
and vice versa. Shorter-maturity bonds are less sensitive.</li>
<li><strong>Borrow cost</strong>: The $\\max(r, 0)$ floor means negative rates don&rsquo;t reduce
borrow costs to zero, but they do reduce the base component.</li>
</ul>

<h3>Event Effects</h3>
<p>In dynamic mode, Fed events directly shift the rate parameters $a$, $b$, and
$\\sigma_R$. A hawkish Fed raises $b$ (pulling rates up); a dovish Fed lowers it.</p>
`,
    },

    vxhcn: {
        title: 'VXHCN (Equity Volatility Index)',
        body: `
<p><strong>VXHCN</strong> is the 30-day equity volatility index for HCN, analogous to
the CBOE&rsquo;s broad-market volatility index but computed for this single stock. It measures the market&rsquo;s
expectation of HCN&rsquo;s volatility over the next 30 trading days.</p>

<h3>How It&rsquo;s Computed</h3>
<p>In the Heston stochastic volatility model, the expected integrated variance
over period $\\Delta = 30/252$ is:</p>
$$\\text{VXHCN}^2 = \\theta + (v - \\theta)\\frac{1 - e^{-\\kappa\\Delta}}{\\kappa\\Delta}$$
<p>where $v$ is the current instantaneous variance, $\\theta$ is the long-run
variance, and $\\kappa$ is the mean-reversion speed. VXHCN is expressed as
an annualised percentage (e.g., 24.5).</p>

<h3>VXHCN Futures</h3>
<p>Tradeable VXHCN futures settle in cash at the VXHCN spot level on their
expiry date. Futures pricing uses the <em>forward</em> variance curve:</p>
$$E[v_T] = \\theta + (v - \\theta)e^{-\\kappa T}$$
<p>This produces natural <strong>contango</strong> (futures above spot) when current
volatility is below long-run levels ($v < \\theta$), and <strong>backwardation</strong>
(futures below spot) when volatility is elevated ($v > \\theta$).</p>

<h3>Trading Uses</h3>
<ul>
<li><strong>Hedging</strong>: Long VXHCN futures hedge a portfolio against volatility spikes.</li>
<li><strong>Carry trade</strong>: Short VXHCN futures in contango to earn the roll-down, at
the risk of a vol spike.</li>
<li><strong>Event plays</strong>: Go long VXHCN before anticipated Fed decisions or
political events to profit from vol expansion.</li>
</ul>
`,
    },

    // -----------------------------------------------------------------------
    // Dynamic Regime Topics
    // -----------------------------------------------------------------------

    events: {
        title: 'Event Engine',
        body: `
<p>The dynamic regime modes generate narrative market events that shift simulation
parameters in real time, creating evolving market conditions and storylines.</p>

<h3>Scheduling</h3>
<table style="width:100%;border-collapse:collapse;margin:12px 0">
<tr><th style="text-align:left;padding:4px 8px">Event type</th><th style="text-align:left;padding:4px 8px">Frequency</th><th style="text-align:left;padding:4px 8px">Notes</th></tr>
<tr><td style="padding:4px 8px">Fed meetings</td><td style="padding:4px 8px">~1 per 32 days</td><td style="padding:4px 8px">With jitter; ~8/year like real FOMC</td></tr>
<tr><td style="padding:4px 8px">Non-Fed events</td><td style="padding:4px 8px">Poisson ~1/30 days</td><td style="padding:4px 8px">8&ndash;15 day cooldown; effective ~1/41.5</td></tr>
<tr><td style="padding:4px 8px">Midterm elections</td><td style="padding:4px 8px">Day 504</td><td style="padding:4px 8px">Campaign from day 440</td></tr>
</table>

<h3>Event Categories</h3>
<ul>
<li><strong>Fed/monetary</strong>: rate decisions, QE/QT, forward guidance</li>
<li><strong>Macro/geopolitical</strong>: GDP, trade wars, conflicts</li>
<li><strong>Sector/tech</strong>: AI breakthroughs, regulation, tech crashes</li>
<li><strong>Market structure</strong>: short squeezes, flash crashes, liquidity events</li>
<li><strong>Neutral/flavour</strong>: colour events that don&rsquo;t significantly move parameters</li>
</ul>

<h3>Parameter Effects</h3>
<p>Each event applies additive deltas to simulation parameters ($\\mu$, $\\theta$, $\\kappa$,
$\\xi$, $\\rho$, $\\lambda$, $\\mu_J$, $\\sigma_J$, $a$, $b$, $\\sigma_R$, $k$, $q$).
Deltas are clamped to <code>PARAM_RANGES</code> to prevent extreme values.
The weighted average across the full event pool is approximately zero,
preventing systematic drift.</p>

<h3>Followup Chains</h3>
<p>Events can schedule followup events with a mean-time-to-happen (MTTH) delay,
sampled from a Poisson distribution. Followups can recursively trigger their own
followups up to 5 levels deep, creating multi-step narrative arcs (e.g., investigation
&rarr; hearing &rarr; verdict &rarr; consequences).</p>

<h3>Boredom Boost</h3>
<p>After 3 consecutive minor/neutral events, the engine boosts the probability of
a significant event firing on the next check, preventing long stretches of
uneventful market action.</p>
`,
    },

    llm: {
        title: 'LLM Integration',
        body: `
<p>The Dynamic (LLM) mode uses Claude to generate contextual market events based on
the simulation&rsquo;s current state, narrative history, and a rich fictional universe.</p>

<h3>How It Works</h3>
<p>The simulation calls the Anthropic API directly from the browser using structured
tool use (<code>emit_events</code> tool with forced <code>tool_choice</code>).
The system prompt contains the full universe lore:</p>
<ul>
<li>President John Barron (Federalist) vs. Robin Clay (Farmer-Labor)</li>
<li>Fed Chair Hayden Hartley&rsquo;s independence and credibility</li>
<li>Geopolitical landscape, congressional composition, ongoing investigations</li>
</ul>
<p>Events are pre-fetched in batches of 3&ndash;5 to minimise API calls and latency.</p>

<h3>Configuration</h3>
<p>Set your Anthropic API key in the Settings tab (stored in <code>localStorage</code>,
never sent anywhere except the Anthropic API). Choose between:</p>
<ul>
<li><strong>Haiku 4.5</strong>: faster, cheaper, good for routine events</li>
<li><strong>Sonnet 4</strong>: more creative narratives and complex multi-step storylines</li>
</ul>

<h3>Context Window</h3>
<p>Each API call includes:</p>
<ul>
<li>Current simulation state (prices, vol, rates, day)</li>
<li>The last 10 events fired (narrative continuity)</li>
<li>Pending followups (plot threads to resolve)</li>
<li>World state (congress, factions, investigations)</li>
</ul>

<h3>Fallback</h3>
<p>If the API call fails (network error, invalid key, rate limit), the engine
automatically falls back to the offline event pool for that batch. The simulation
continues seamlessly &mdash; you just get curated events instead of generated ones.</p>
`,
    },
};
